*

!package.json
!package-lock.json
!tsconfig.json
!scripts/
!scripts/**

!webpack.config.mjs
!postcss.config.mjs
!tailwind.config.mjs
!components.json
!shadcn/
!shadcn/**
!public/
!public/**
!src/
!src/**
